### ISSUE TITLE
Support http status 201 created

### ISSUE THREAD

**Issue by JMLamodiere** [CircleOfNice/DoctrineRestDriver#12]
#### What is this feature about (expected vs actual behaviour)?
When performing a POST call, the HTTP code commonly used is `201 created`. Currently, the library only accepts `200 OK`.

As REST is not a standard, we should probably avoid being too strict, and accept both to add flexibility.

#### How can I reproduce it?
Persist new entity with an API returning `201`.

#### Does it take minutes, hours or days to fix?
Minutes. Steps : 
 - Fix `Circle\DoctrineRestDriver\Statement::execute` method
 - Fix documentation

**Comment by TobiasHauck** [comment]
Thanks for reporting. You are right. 201 is even a better status than 200. We should accept both. Would you mind opening a pull request?

**Comment by JMLamodiere** [comment]
Ok I'll open it

**Comment by JMLamodiere** [comment]
Sorry for the delay. I was going to fix it, but after running tests with PHP 5.5, I've opened a new issue #14 :)

**Comment by TobiasHauck** [comment]
Any news about this issue? If you don't have the time to complete it you can also open a PR including the current state of the branch you've been working on, so we are able to complete it.

**Comment by TobiasHauck** [comment]
#33 is a bit related to this issue. Anyways: 201 for POST should be accepted by default.

**Comment by JMLamodiere** [comment]
Oh sorry, did'nt received the previous comment.

I'm currently in holidays. Could someone else handle this issue?
