### ISSUE TITLE
Usage of PHP 5.6 constant ARRAY_FILTER_USE_KEY

### ISSUE THREAD

**Issue by JMLamodiere** [CircleOfNice/DoctrineRestDriver#14]
#### What is this feature about (expected vs actual behaviour)?
According to [composer.json](https://github.com/CircleOfNice/DoctrineRestDriver/blob/master/composer.json#L36), this library requires php >=5.5. But the class [Circle\DoctrineRestDriver\Types\CurlOptions](https://github.com/CircleOfNice/DoctrineRestDriver/blob/master/Types/CurlOptions.php#L60) uses the constant `ARRAY_FILTER_USE_KEY`. It exists since PHP 5.6, according to [array_filter doc](http://php.net/manual/en/function.array-filter.php).

We must either find a workaround for PHP 5.5, or change minimal version in `composer.json`. PHP 5.5 security support [ends in 3 months](http://php.net/supported-versions.php), but is still widely used. I suggest the 5.5 workaround.

#### How can I reproduce it?

Launch the unit tests with PHP 5.5.

#### Does it take minutes, hours or days to fix?

Minutes

#### Any additional information?

I can handle the PR if needed :)

**Comment by TobiasHauck** [comment]
First of all thanks for the detailed information, especially the links. Maybe we should try to find an elegant solution without ```ARRAY_FILTER_USE_KEY``` (only [ array functions ] (http://php.net/manual/de/ref.array.php), no usage of ```foreach```). If that's possible let's stay with PHP 5.5 regarding your arguments.

Would be great if you handled the PR ;) Thanks again!
