### ISSUE TITLE
Whole URL in Table annotation is not working

### ISSUE THREAD

**Issue by mattsches** [CircleOfNice/DoctrineRestDriver#23]
#### What is this feature about (expected vs actual behaviour)?
In the README it says that when creating an entity: 

> You can either only use a resource name or the whole url of the resource to define your target.

The second case using the whole url does not work for me. This is [my entity
](https://gist.github.com/mattsches/67706fe97695341a4cf195ed3cde52a9) with the whole url in the annotation. Using just `albums` and defining `default_api_url: http://jsonplaceholder.typicode.com` in `parameters.yml` works just fine.

#### How can I reproduce it?

Use the entity mentioned above and create a simple controller action, e.g.
```php
    /**
     * @Route("/album/readAll", name="album_read_all")
     */
    public function readAllAction()
    {
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository('AppBundle\Entity\Album')->findAll();
        $result = array_map(
            function (\AppBundle\Entity\Album $album) {
                return $album->getTitle();
            },
            $entities
        );

        return new Response(implode(', ', $result));
    }
```

This will result in a `DBALException: An exception occurred while executing 'SELECT t0.userId AS userId_1, t0.id AS id_2, t0.title AS title_3 FROM http://jsonplaceholder.typicode.com/albums t0': Notice: Undefined index: t0.userId`

#### Does it take minutes, hours or days to fix?

It probably has sth. to do with `PHPSQLParser`, but I couldn't figure it out at once. May take between minutes and hours to fix ;)

#### Any additional information?

Maybe I got it all wrong. If so, please explain and close the issue ;)

**Comment by TobiasHauck** [comment]
Hi Matthias, thanks for reporting the issue. I found out what's going wrong here:

The PHPSQLParser is only able to tokenize a query with a table name containing special characters if the table name is quoted. In general I don't want to quote the whole table name. The table name should be either a name containing letters or an URL. So each time the table name is an URL (asserted by the "isUrl" function in Validation/Assertions) the table name should be quoted.

The ```isUrl``` function returns ```false``` for the given URL which is wrong. So to fix this problem we have to change the regular expression of the ```isUrl``` function.

Additionally we should throw an invalid table name exception if the table name is neither an URL nor a regular name.

**Comment by TobiasHauck** [comment]
This one should do the trick:

``` (http|ftp|https):\/\/([\w-])+(\.[\w-]+)?([\w.,@?^=%&amp;:/~+#-]*[\w@?^=%&amp;/~+#-])? ```

May you be so kind and open a pull request? Thanks!

**Comment by mattsches** [comment]
Funny thing is, if I add the URL to the test
```php
public function isUrlTest() {
        $this->assertTrue(Assertions::isUrl('http://www.circle.ai'));
        $this->assertTrue(Assertions::isUrl('http://jsonplaceholder.typicode.com/albums'));
    }
```
the test is still green (with both regexes). 

And my query isn't working with both regexes. I might have to take a closer look at what's going on, but on the other hand, everything works fine if I set `default_api_url` correctly …

**Comment by TobiasHauck** [comment]
Any news about this issue? If you don't have the time to complete it you can also open a PR including the current state of the branch you've been working on, so we are able to complete it.

**Comment by mattsches** [comment]
I think I've narrowed it down a bit. When executing a query, the query is transformed before being converted into a Request. Especially, quotes are added around the URL in `$transformedQuery`: https://github.com/CircleOfNice/DoctrineRestDriver/blob/master/Transformers/MysqlToRequest.php#L94

However, when creating/hydrating the result (https://github.com/CircleOfNice/DoctrineRestDriver/blob/master/Types/Result.php#L42) this is not happening, so the quotes around the URL are missing in `$query` (we don't have a `$transformedQuery` here).
Because of this difference, `PHPSQLParser::parse()`, or to be more specific, `DefaultProcessor::process()` returns a different set of tokens; it doesn't regard the URL as one string but explodes the slashes, too.

If I add the transformQuery stuff to `Result::create()` like in the following snippet, everything works fine.
```
public static function create($query, $content) {
    // copied & pasted code start
        $params = [];
        $query = array_reduce($params, function($query, $param) {
            return strpos($query, '?') ? substr_replace($query, $param, strpos($query, '?'), strlen('?')) : $query;
        }, $query);

        $queryParts = explode(' ', $query);
        $transformedQuery = array_reduce($queryParts, function($carry, $part) {
            return $carry . (Assertions::isUrl($part) ? (' "' . $part . '" ') : ($part . ' '));
        });
    // copied & pasted code end
        $parser   = new PHPSQLParser();
        $tokens   = $parser->parse($transformedQuery); // replaced $query with $transformedQuery
        $operator = strtolower(array_keys($tokens)[0]);

        if ($operator === SqlOperations::DELETE) return [];
        return $operator === SqlOperations::SELECT ? SelectResult::create($tokens, $content) : $content;
    }
```

Of course, this is just copied & pasted code from the `MysqlToRequest` class and thus duplicated code, but you should be able to work out a clean solution, I guess :smile:

**Comment by TobiasHauck** [comment]
That's exactly what's causing this issue. Thanks a lot again, I will work this out in #37 by introducing a new type SqlQuery which bundles the copy&paste code
