### ISSUE TITLE
Support HTTP method PATCH

### ISSUE THREAD

**Issue by robwasripped** [CircleOfNice/DoctrineRestDriver#54]
#### What is this feature about (expected vs actual behaviour)?
The driver does not currently support PATCH as an HTTP method. The style in which doctrine updates (ie updating only the altered fields of an entity) does not match up with the rules of a PUT request which this driver currently performs.

#### How can I reproduce it?
Any "update" query will attempt a PUT request.

#### Does it take minutes, hours or days to fix?
Hours/days

#### Any additional information?
Many APIs do not support PATCH, so this fix could include a configuration option to toggle PATCH requests.

**Comment by TobiasHauck** [comment]
You're totally right

**Comment by robwasripped** [comment]
I will write up a pull request for you to consider if you're in agreement.

**Comment by TobiasHauck** [comment]
Ok cool. Im not sure if the rest client is able to send patch requests, but i think so. Thanks a lot!
