### ISSUE TITLE
Send entire entity in PUT request

### ISSUE THREAD

**Issue by robwasripped** [CircleOfNice/DoctrineRestDriver#59]
#### What is this feature about (expected vs actual behaviour)?
By REST specifications, a PUT request should send the entire entity, not just a partial as it does right now.

#### How can I reproduce it?
Perform an update to an existing entity with the "use_patch" configuration option set to false. The request will be a PUT with only updated properties in the body.

#### Does it take minutes, hours or days to fix?
hours

#### Any additional information?
Relates to #54 #57

**Comment by TobiasHauck** [comment]
Has been fixed more than 1 year ago
