### ISSUE TITLE
Whitespace in query parameters

### ISSUE THREAD

**Issue by robwasripped** [CircleOfNice/DoctrineRestDriver#60]
#### What is this feature about (expected vs actual behaviour)?
When parsing SQL WHERE conditions, whitespace between the operand and operator may be stored as part of the parsed key and value. These keys and values can therefore be invalid.

#### How can I reproduce it?
I'm not sure whether this is specific to newer release of Doctrine or not, but a freshly installed set of packages and an UPDATE query will generate key/value pairs that contain the whitespace from the SQL query.

#### Does it take minutes, hours or days to fix?
minutes

**Comment by TobiasHauck** [comment]
awesome
