### ISSUE TITLE
Query the REST api

### ISSUE THREAD

**Issue by sabloger** [CircleOfNice/DoctrineRestDriver#71]
How can i do a query with fields and values (like SQL query) with RestDriver?

**Comment by sabloger** [comment]
And can i use it inside of Standard Doctrine model?

**Comment by TobiasHauck** [comment]
Hi Saeed,

have a look at the functional test:
https://github.com/CircleOfNice/DoctrineRestDriver/blob/master/Tests/FunctionalTest.php#L226

As you can see you can also write native queries and they are mapped to the corresponding REST API endpoint. Maybe we should add this to the readme.

**Comment by TobiasHauck** [comment]
#78 README add native queries
