### ISSUE TITLE
Problems unserializing json fields

### ISSUE THREAD

**Issue by thefuriouscoder** [CircleOfNice/DoctrineRestDriver#87]
Hi there,

I'm having a bit trouble putting the thing to work, maybe you can help me, I don´t know which Doctrine type should I use to serialize/unserialize a JSON object, I think it is more clear with an example.

Having this API response:
```json
{
  "id": "0022c1cc-8b42-41e6-99eb-07523998d2cb",
  "label": "ROLE_ADMIN",
  "name": "Admin",
  "description": "Admins are allowed to do pretty much anything within the app. This role should be only assigned to TVL tech team.",
  "permissions": {
    "Company": {
      "create": true,
      "edit": true,
      "view": true,
      "delete": true
    },
    "User": {
      "create": true,
      "edit": true,
      "view": true,
      "delete": true
    },
    "Account": {
      "create": true,
      "edit": true,
      "view": true,
      "delete": true
    }
  }
}
```
and this entity defined:

```php
/**
 * This annotation marks the class as managed entity:
 *
 * @ORM\Entity
 * @ORM\Table("roles")
 */
class Role
{
    /**
     * @var UuidInterface $id
     * @JMS\Type("uuid")
     * @ORM\Column(type="uuid", unique=true, length=36)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     * @ORM\Id
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @JMS\Type("string")
     * @var string $label
     */
    private $label;

    /**
     * @ORM\Column(type="string", length=100)
     * @JMS\Type("string")
     * @var string $name
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100)
     * @JMS\Type("string")
     * @var string $description
     */
    private $description;

    /**
     * @ORM\Column(type="array")
     * @JMS\Type("array")
     * @var array
     */
    private $permissions = [];
```

it works everything ok except the unserialization of the field permissions, I´ve tried with json, json_array, array and object as Doctrine types but no one works, when the code reaches the convertToPHPValue call inside Doctrine type, the value, in this case, an array, is already unserialized to array by a previous json_decode in the formatter class throwing the following exception:

```json
{
  "code": 500,
  "message": "Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize() expects parameter 1 to be string, array given'"
}
```

I suppose this is a silly thing, but I´m unable to fix it.

Hope someone can help me.

Regards, Diego.

**Comment by TobiasHauck** [comment]
Hi Diego,
The response of the API doesn't seem to be an array, but an object/hashmap. Are you able to modify the API?

**Comment by thefuriouscoder** [comment]
Hi Tobias,

thanks for your reply, I have access to the API so I could change the API response, but the problem is that the Doctrine type convertToPHPValue method expects an unserializable string as input and due to the json_decode performed by the formatter it always receives an object or an array.  I'm going to implement and register a new Doctrine type that will not transform the input received if already it is a valid php type. I think it will do the work.

Thanks for help.

**Comment by thefuriouscoder** [comment]
Using a custom Doctrine type this issue could be fixed. If anyone is interested in this, please let me now.
